@startuml
title Asset Extractor Class Diagram

package "asset_extractor" as pAssetExtractor {

    class "asset_extractor.core.AssetExtractor" as cAssetExtractor {
        conf
        +export(asset: dict) -> None
        +process_file(filename: str, media_type: str, processing_level: str) -> None
    }

    abstract class "asset_extractor.handlers.BaseHandlerPicker" as cBaseHandlerPicker {

    }

    abstract class "asset_extractor.handlers.BaseMediaHandler" as cBaseMediaHandler {
        +get_metadata(file, *args, *kwargs) -> dict
    }


    class "asset_extractor.handlers.media.POSIXHandler" as cPOSIXHandler {}
    class "asset_extractor.handlers.media.TapeHandler" as cTapeHandler {}
    class "asset_extractor.handlers.media.ObjectStoreHandler" as cObjectStoreHandler {}

    cPOSIXHandler <|-- cBaseMediaHandler
    cTapeHandler <|-- cBaseMediaHandler
    cObjectStoreHandler <|-- cBaseMediaHandler
}



@enduml