@startuml
title Asset Extractor Class Diagram

package "asset_extractor" as pAssetExtractor {

    class "asset_extractor.core.AssetExtractor" as cAssetExtractor {
        conf
        +export(asset: dict) -> None
        +process_file(filename: str, media_type: str, processing_level: str) -> None
    }

    abstract class "asset_extractor.handlers.BaseHandlerPicker" as cBaseHandlerPicker {

    }

    abstract class "asset_extractor.handlers.BaseFileHandler" as cBaseFileHandler {
    }

    abstract class "asset_extractor.handlers.BaseMediaHandler" as cBaseMediaHandler {
    }

}

package "file_handlers" as pFileHandlers {
    class GenericFile {
        +get_metadata_level1(file_obj) -> dict
        +get_metadata_level2(file_obj) -> dict
        +get_metadata_level3(file_obj) -> dict
        +get_metadata(file_obj, level: str) -> dict
    }

    class NetCDFFile
    class BADCCSVFile
    class ESASafeFile
    class GRIBFile
    class HDFFile
    class KMZFile
    class JSONFile
    class NASAAmesFile
    class PPFile

    GenericFile <|-- cBaseFileHandler
    NetCDFFile <|-- GenericFile
    BADCCSVFile <|-- GenericFile
    ESASafeFile <|-- GenericFile
    GRIBFile <|-- GenericFile
    HDFFile <|-- GenericFile
    KMZFile <|-- GenericFile
    JSONFile <|-- GenericFile
    NASAAmesFile <|-- GenericFile
    PPFile <|-- GenericFile
}



@enduml