@startuml
title Asset Extractor Component Diagram



note bottom of pMediaHandlers
    _id
    size
    extension
    mtime
    magic number?
    media type
    filepath_type_location
    filename
    checksums {
        time:
        checksum
    }
end note

package "Media Handlers" as pMediaHandlers {
    component "Tape Handler" as cpTapeHandler
    component "POSIX Handler" as cpPOSIXHandler
    component "Object Store Handler" as cpObjectStoreHandler
    component "Media Handler Picker" as cpMediaHandlerPicker
}
interface "Media Handler API" as ifMediaHandlerAPI
cpMediaHandlerPicker -up-() ifMediaHandlerAPI

component "AssetStorageBackend" as cpStorageBackend {
    component "Elasticsearch Storage Backend" as cpElasticsearchBackend
    component "RabbitMQ Backend" as cpRabbitMQBackend
}

interface "StorageBackendAPI" as ifStorageBackendAPI
cpStorageBackend -up-() ifStorageBackendAPI

database "Elasticsearch" as cpElasticsearch
interface "Elasticsearch API" as ifElasticsearch
cpElasticsearch -up-() ifElasticsearch

node "Rabbit MQ" as cpRabbitMQ
interface "RabbitMQ API" as ifRabbitMQ
cpRabbitMQ -up-() ifRabbitMQ

component "Logstash" as cpLogstash
cpLogstash -left-( ifRabbitMQ
cpLogstash -right-( ifElasticsearch

component "Asset Extractor" as cpAssetExtractor
interface "process_file()" as ifAssetProcessFile

component "List Source"  as cpListSource {
    component "RabbitMQConsumer" as cpRabbitConsumer
}

node "RabbitMQ" as nRabbitMQ2
interface "RabbitMQ API" as ifRabbitMQ2

cpListSource -right-( ifAssetProcessFile
nRabbitMQ2 -right-() ifRabbitMQ2
cpRabbitConsumer -up-( ifRabbitMQ2

' Asset extractor apis
cpAssetExtractor -right-( ifStorageBackendAPI
cpAssetExtractor -down-( ifMediaHandlerAPI
cpAssetExtractor -left-() ifAssetProcessFile

' Asset storeage backend connections
cpRabbitMQBackend -down-( ifRabbitMQ
cpElasticsearchBackend -down-( ifElasticsearch


@enduml